### ISSUE TITLE
[MAJOR BUG] Most foliage doesn't generate

### ISSUE THREAD

**Issue by BlueIsADude** [Silversmith-Mods/Grounded#1]
Downloaded this mod because it seemed really cool (big fan of the textures!), but unfortunately theres an insanely big issue with it right now thats keeping me from being able to use it.
When the mod is installed, foliage like tall grass, flowers, and even trees will just completely refuse to generate.
![2024-12-02_22 17 06](https://github.com/user-attachments/assets/fc9196e4-7c82-404a-93b6-b7b81639d4c1)
(screenshot of a freshly generated world, with the fabric version of the mod enabled.)
![2024-12-02_22 25 20](https://github.com/user-attachments/assets/cbfb268d-3c08-475e-b9e4-6f6e6716c270)
(screenshot of the same exact world, but generated without the mod)

The only mods I had installed were Fabric API, Mod Menu, Grounded, and Moonlight Lib. I did only test on fabric, but I will also be checking on forge as well.

**Comment by AstralOrdana** [comment]
i know about this, i have no idea why its happening and i could have sworn it was fine when i tested it before release
im still working on fixing it

**Comment by BlueIsADude** [comment]
Thats a shame. I wish you luck with fixing it! I know mod dev is hard, but i hope you'll be able to figure out the issue!
I'll try to help any way i can in the meantime.

**Comment by AstralOrdana** [comment]
FIXED for 0.1.1
