### ISSUE TITLE
Better Immersive Wearthering compatibility

### ISSUE THREAD

**Issue by thwonn** [Silversmith-Mods/Grounded#5]
When I use this mod with Immersive Weathering, there is a lot of overlap between the two mods. Would it be possible to remove all the Grounded blocks from Immersive Weathering and make Grounded an optional dependency so I can use both mods?

**Comment by AstralOrdana** [comment]
iw and grounded arent intended to be used at the same time in 1.20.1, of course there's feature overlap thats the entire point of Grounded. the soils will be removed from iw in future updates

**Comment by thwonn** [comment]
ok then because I want the content from both in the same modpack
